#!/public/home/liujf/software/program/R-4.3.1-no-dev/bin/Rscript

########################################################################################################################
## Version: 1.3.0
## Author:    Liweining liwn@cau.edu.cn
## Orcid:     0000-0002-0578-3812
## Institute: College of Animal Science and Technology, China Agricul-tural University, Haidian, 100193, Beijing, China
## Date:      2024-08-20
##
## Function：
## Perform PCA plotting based on the plink feature vector results
##
##
## Usage: ./PCA_plot.R --eigv "/path/to/eigv/file" ...(Please refer to --help for detailed parameters)
##
## License:
##  This script is licensed under the GPL-3.0 License.
##  See https://www.gnu.org/licenses/gpl-3.0.en.html for details.
########################################################################################################################

## Load packages
cat("Loading packages needed...\n")
suppressPackageStartupMessages(library("Cairo", warn.conflicts = FALSE))
suppressPackageStartupMessages(library("ggplot2", warn.conflicts = FALSE))
suppressPackageStartupMessages(library("getopt", warn.conflicts = FALSE))

## Command-line parameters
spec <- matrix(
  c(
    "eigv",  "I", 2, "character", "[Required] eigenvector file generated by Plink",
    "group", "G", 2, "character", "[Optional] populations/group names",
    "out",   "O", 2, "character", "[Optional] output result prefix",
    "help",  "h", 0, "logical",   "This is Help!"
  ),
  byrow = TRUE, ncol = 5
)
opt <- getopt(spec = spec)

## Check parameters
if (!is.null(opt$help) || is.null(opt$eigv)) {
  cat(paste(getopt(spec = spec, usage = TRUE), "\n"))
  quit()
}

## The PCA results calculated by plink
pca <- read.table(opt$eigv, header = TRUE)

## Check if there is a title in the PCA result file
if (names(pca)[1] != "FID") {
  pca <- read.table(opt$eigv, header = FALSE)
  names(pca)[1:4] <- c("IID", "FID", "PC1", "PC2")
}

## Group information
if (is.null(opt$group)) {
  if (identical(pca$FID, pca$IID)) {
    if (ncol(pca) > 5) {
      names(pca)[6] <- c("group")
    } else {
      cat("Please provide the IID-FID match file.")
      quit()
    }
  } else {
    names(pca)[which(names(pca) == "FID")] <- "group"
  }
} else {
  group <- read.table(opt$group, header = TRUE)
  names(group) <- c("IID", "group")
  pca <- merge(pca, group, by = "IID")
}

## File name
if (is.null(opt$out)) {
  output <- paste0("PCA_", unique(pca$group)[1], "_", unique(pca$group)[2], ".png")
} else {
  output <- paste0(opt$out, ".png")
}

## Plot based on principal components 1 and 2
# png(output, width = 800, height = 600, bg = "white")
CairoPNG(output, width = 800, height = 600, bg = "white")

ggplot(pca, aes(x = PC1, y = PC2, colour = group, shape = group)) +
  geom_point(size = 1.5) +
  theme(
    axis.text.x = element_text(colour = "black", size = 14),
    axis.text.y = element_text(size = 14, face = "plain"),
    axis.title.x = element_text(size = 14, face = "plain"),
    axis.title.y = element_text(size = 14, face = "plain"),
    legend.text = element_text(size = 26),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  xlab("Principal component 1") +
  ylab("Principal component 2")

hide_message <- dev.off()
cat("PCA plot successfully.\n")
